events {}

http {
    fastcgi_read_timeout 300;
    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;

    upstream backend_servers {
        server app_1:9000;
        server app_2:9000;
        server app_3:9000;
        server app_4:9000;
        server app_5:9000;
        server app_6:9000;
        server app_7:9000;
    }

    server {
        listen 80;
        
        root /app/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass backend_servers;
            fastcgi_index index.php;
            include fastcgi_params;
            
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
}